export interface Employee {
  id: number;
  username: string;
  firstName: string;
  lastName: string;
  email: string;
  birthDate: Date;
  basicSalary: number;
  status: string;
  group: string;
  description: Date;
}

export const dataEmployee: Employee[] = [
  {
    id: 1,
    username: 'john_doe',
    firstName: 'John',
    lastName: 'Doe',
    email: 'john.doe@example.com',
    birthDate: new Date('1990-01-15'),
    basicSalary: 60000,
    status: 'Active',
    group: 'Engineering',
    description: new Date('2022-01-01'),
  },
  {
    id: 2,
    username: 'jane_smith',
    firstName: 'Jane',
    lastName: 'Smith',
    email: 'jane.smith@example.com',
    birthDate: new Date('1988-05-20'),
    basicSalary: 75000,
    status: 'Active',
    group: 'Sales',
    description: new Date('2022-01-05'),
  },
  {
    id: 3,
    username: 'bob_jones',
    firstName: 'Bob',
    lastName: 'Jones',
    email: 'bob.jones@example.com',
    birthDate: new Date('1995-09-10'),
    basicSalary: 50000,
    status: 'Inactive',
    group: 'Marketing',
    description: new Date('2022-02-10'),
  },
  // Data 4-50
  {
    id: 4,
    username: 'emma_wilson',
    firstName: 'Emma',
    lastName: 'Wilson',
    email: 'emma.wilson@example.com',
    birthDate: new Date('1993-04-25'),
    basicSalary: 62000,
    status: 'Active',
    group: 'Engineering',
    description: new Date('2022-03-01'),
  },
  {
    id: 5,
    username: 'michael_thomas',
    firstName: 'Michael',
    lastName: 'Thomas',
    email: 'michael.thomas@example.com',
    birthDate: new Date('1987-11-15'),
    basicSalary: 72000,
    status: 'Active',
    group: 'Sales',
    description: new Date('2022-03-05'),
  },
  {
    id: 6,
    username: 'olivia_taylor',
    firstName: 'Olivia',
    lastName: 'Taylor',
    email: 'olivia.taylor@example.com',
    birthDate: new Date('1992-07-08'),
    basicSalary: 58000,
    status: 'Active',
    group: 'Engineering',
    description: new Date('2022-03-10'),
  },
  {
    id: 7,
    username: 'william_miller',
    firstName: 'William',
    lastName: 'Miller',
    email: 'william.miller@example.com',
    birthDate: new Date('1994-02-18'),
    basicSalary: 67000,
    status: 'Active',
    group: 'Marketing',
    description: new Date('2022-03-15'),
  },
  {
    id: 8,
    username: 'sophia_martin',
    firstName: 'Sophia',
    lastName: 'Martin',
    email: 'sophia.martin@example.com',
    birthDate: new Date('1990-06-22'),
    basicSalary: 69000,
    status: 'Active',
    group: 'Engineering',
    description: new Date('2022-03-20'),
  },
  {
    id: 9,
    username: 'james_brown',
    firstName: 'James',
    lastName: 'Brown',
    email: 'james.brown@example.com',
    birthDate: new Date('1988-12-05'),
    basicSalary: 71000,
    status: 'Active',
    group: 'Sales',
    description: new Date('2022-03-25'),
  },
  {
    id: 10,
    username: 'emily_campbell',
    firstName: 'Emily',
    lastName: 'Campbell',
    email: 'emily.campbell@example.com',
    birthDate: new Date('1993-09-30'),
    basicSalary: 64000,
    status: 'Active',
    group: 'Engineering',
    description: new Date('2022-03-30'),
  },
  {
    id: 11,
    username: 'benjamin_thompson',
    firstName: 'Benjamin',
    lastName: 'Thompson',
    email: 'benjamin.thompson@example.com',
    birthDate: new Date('1989-04-12'),
    basicSalary: 73000,
    status: 'Active',
    group: 'Marketing',
    description: new Date('2022-04-01'),
  },
  {
    id: 12,
    username: 'ava_hall',
    firstName: 'Ava',
    lastName: 'Hall',
    email: 'ava.hall@example.com',
    birthDate: new Date('1995-01-28'),
    basicSalary: 65000,
    status: 'Active',
    group: 'Engineering',
    description: new Date('2022-04-05'),
  },
  {
    id: 13,
    username: 'william_anderson',
    firstName: 'William',
    lastName: 'Anderson',
    email: 'william.anderson@example.com',
    birthDate: new Date('1992-07-15'),
    basicSalary: 71000,
    status: 'Active',
    group: 'Sales',
    description: new Date('2022-04-10'),
  },
  {
    id: 14,
    username: 'grace_adams',
    firstName: 'Grace',
    lastName: 'Adams',
    email: 'grace.adams@example.com',
    birthDate: new Date('1987-11-08'),
    basicSalary: 68000,
    status: 'Active',
    group: 'Engineering',
    description: new Date('2022-04-15'),
  },
  {
    id: 15,
    username: 'logan_harris',
    firstName: 'Logan',
    lastName: 'Harris',
    email: 'logan.harris@example.com',
    birthDate: new Date('1994-03-22'),
    basicSalary: 72000,
    status: 'Active',
    group: 'Marketing',
    description: new Date('2022-04-20'),
  },
  {
    id: 16,
    username: 'mia_cook',
    firstName: 'Mia',
    lastName: 'Cook',
    email: 'mia.cook@example.com',
    birthDate: new Date('1991-05-10'),
    basicSalary: 67000,
    status: 'Active',
    group: 'Engineering',
    description: new Date('2022-04-25'),
  },
  {
    id: 17,
    username: 'oliver_morgan',
    firstName: 'Oliver',
    lastName: 'Morgan',
    email: 'oliver.morgan@example.com',
    birthDate: new Date('1986-09-18'),
    basicSalary: 69000,
    status: 'Active',
    group: 'Sales',
    description: new Date('2022-05-01'),
  },
  {
    id: 18,
    username: 'amelia_nelson',
    firstName: 'Amelia',
    lastName: 'Nelson',
    email: 'amelia.nelson@example.com',
    birthDate: new Date('1993-02-05'),
    basicSalary: 66000,
    status: 'Active',
    group: 'Engineering',
    description: new Date('2022-05-05'),
  },
  {
    id: 19,
    username: 'ethan_carter',
    firstName: 'Ethan',
    lastName: 'Carter',
    email: 'ethan.carter@example.com',
    birthDate: new Date('1988-10-20'),
    basicSalary: 70000,
    status: 'Active',
    group: 'Marketing',
    description: new Date('2022-05-10'),
  },
  {
    id: 20,
    username: 'mia_rivera',
    firstName: 'Mia',
    lastName: 'Rivera',
    email: 'mia.rivera@example.com',
    birthDate: new Date('1992-04-15'),
    basicSalary: 71000,
    status: 'Active',
    group: 'Engineering',
    description: new Date('2022-05-15'),
  },
  {
    id: 21,
    username: 'mason_cooper',
    firstName: 'Mason',
    lastName: 'Cooper',
    email: 'mason.cooper@example.com',
    birthDate: new Date('1989-11-28'),
    basicSalary: 68000,
    status: 'Active',
    group: 'Sales',
    description: new Date('2022-05-20'),
  },
  {
    id: 22,
    username: 'ava_gomez',
    firstName: 'Ava',
    lastName: 'Gomez',
    email: 'ava.gomez@example.com',
    birthDate: new Date('1995-08-12'),
    basicSalary: 67000,
    status: 'Active',
    group: 'Engineering',
    description: new Date('2022-05-25'),
  },
  {
    id: 23,
    username: 'noah_russell',
    firstName: 'Noah',
    lastName: 'Russell',
    email: 'noah.russell@example.com',
    birthDate: new Date('1990-01-30'),
    basicSalary: 70000,
    status: 'Active',
    group: 'Marketing',
    description: new Date('2022-06-01'),
  },
  {
    id: 24,
    username: 'sophia_hernandez',
    firstName: 'Sophia',
    lastName: 'Hernandez',
    email: 'sophia.hernandez@example.com',
    birthDate: new Date('1987-05-25'),
    basicSalary: 69000,
    status: 'Active',
    group: 'Engineering',
    description: new Date('2022-06-05'),
  },
  {
    id: 25,
    username: 'aiden_richardson',
    firstName: 'Aiden',
    lastName: 'Richardson',
    email: 'aiden.richardson@example.com',
    birthDate: new Date('1994-10-08'),
    basicSalary: 72000,
    status: 'Active',
    group: 'Sales',
    description: new Date('2022-06-10'),
  },
  {
    id: 26,
    username: 'olivia_cox',
    firstName: 'Olivia',
    lastName: 'Cox',
    email: 'olivia.cox@example.com',
    birthDate: new Date('1991-03-22'),
    basicSalary: 67000,
    status: 'Active',
    group: 'Engineering',
    description: new Date('2022-06-15'),
  },
  {
    id: 27,
    username: 'ethan_ross',
    firstName: 'Ethan',
    lastName: 'Ross',
    email: 'ethan.ross@example.com',
    birthDate: new Date('1986-08-18'),
    basicSalary: 70000,
    status: 'Active',
    group: 'Marketing',
    description: new Date('2022-06-20'),
  },
  {
    id: 28,
    username: 'isabella_howard',
    firstName: 'Isabella',
    lastName: 'Howard',
    email: 'isabella.howard@example.com',
    birthDate: new Date('1993-11-05'),
    basicSalary: 69000,
    status: 'Active',
    group: 'Engineering',
    description: new Date('2022-06-25'),
  },
  {
    id: 29,
    username: 'owen_bell',
    firstName: 'Owen',
    lastName: 'Bell',
    email: 'owen.bell@example.com',
    birthDate: new Date('1988-06-20'),
    basicSalary: 71000,
    status: 'Active',
    group: 'Sales',
    description: new Date('2022-07-01'),
  },
  {
    id: 30,
    username: 'emma_hall',
    firstName: 'Emma',
    lastName: 'Hall',
    email: 'emma.hall@example.com',
    birthDate: new Date('1995-01-15'),
    basicSalary: 68000,
    status: 'Active',
    group: 'Engineering',
    description: new Date('2022-07-05'),
  },
  {
    id: 31,
    username: 'samuel_diaz',
    firstName: 'Samuel',
    lastName: 'Diaz',
    email: 'samuel.diaz@example.com',
    birthDate: new Date('1990-04-30'),
    basicSalary: 70000,
    status: 'Active',
    group: 'Marketing',
    description: new Date('2022-07-10'),
  },
  {
    id: 32,
    username: 'chloe_russell',
    firstName: 'Chloe',
    lastName: 'Russell',
    email: 'chloe.russell@example.com',
    birthDate: new Date('1987-09-15'),
    basicSalary: 67000,
    status: 'Active',
    group: 'Engineering',
    description: new Date('2022-07-15'),
  },
  {
    id: 33,
    username: 'joseph_gomez',
    firstName: 'Joseph',
    lastName: 'Gomez',
    email: 'joseph.gomez@example.com',
    birthDate: new Date('1994-02-28'),
    basicSalary: 72000,
    status: 'Active',
    group: 'Sales',
    description: new Date('2022-07-20'),
  },
  {
    id: 34,
    username: 'scarlett_carter',
    firstName: 'Scarlett',
    lastName: 'Carter',
    email: 'scarlett.carter@example.com',
    birthDate: new Date('1991-07-10'),
    basicSalary: 69000,
    status: 'Active',
    group: 'Engineering',
    description: new Date('2022-07-25'),
  },
  {
    id: 35,
    username: 'daniel_ramirez',
    firstName: 'Daniel',
    lastName: 'Ramirez',
    email: 'daniel.ramirez@example.com',
    birthDate: new Date('1986-12-25'),
    basicSalary: 71000,
    status: 'Active',
    group: 'Marketing',
    description: new Date('2022-08-01'),
  },
  {
    id: 36,
    username: 'madison_stewart',
    firstName: 'Madison',
    lastName: 'Stewart',
    email: 'madison.stewart@example.com',
    birthDate: new Date('1993-03-08'),
    basicSalary: 68000,
    status: 'Active',
    group: 'Engineering',
    description: new Date('2022-08-05'),
  },
  {
    id: 37,
    username: 'jaxon_lopez',
    firstName: 'Jaxon',
    lastName: 'Lopez',
    email: 'jaxon.lopez@example.com',
    birthDate: new Date('1988-10-20'),
    basicSalary: 70000,
    status: 'Active',
    group: 'Sales',
    description: new Date('2022-08-10'),
  },
  {
    id: 38,
    username: 'victoria_hall',
    firstName: 'Victoria',
    lastName: 'Hall',
    email: 'victoria.hall@example.com',
    birthDate: new Date('1995-05-05'),
    basicSalary: 67000,
    status: 'Active',
    group: 'Engineering',
    description: new Date('2022-08-15'),
  },
  {
    id: 39,
    username: 'lucas_wright',
    firstName: 'Lucas',
    lastName: 'Wright',
    email: 'lucas.wright@example.com',
    birthDate: new Date('1990-08-18'),
    basicSalary: 72000,
    status: 'Active',
    group: 'Marketing',
    description: new Date('2022-08-20'),
  },
  {
    id: 40,
    username: 'aubrey_kelly',
    firstName: 'Aubrey',
    lastName: 'Kelly',
    email: 'aubrey.kelly@example.com',
    birthDate: new Date('1987-01-30'),
    basicSalary: 69000,
    status: 'Active',
    group: 'Engineering',
    description: new Date('2022-08-25'),
  },
  {
    id: 41,
    username: 'hudson_cook',
    firstName: 'Hudson',
    lastName: 'Cook',
    email: 'hudson.cook@example.com',
    birthDate: new Date('1994-06-15'),
    basicSalary: 71000,
    status: 'Active',
    group: 'Sales',
    description: new Date('2022-09-01'),
  },
  {
    id: 42,
    username: 'paisley_morris',
    firstName: 'Paisley',
    lastName: 'Morris',
    email: 'paisley.morris@example.com',
    birthDate: new Date('1991-11-28'),
    basicSalary: 68000,
    status: 'Active',
    group: 'Engineering',
    description: new Date('2022-09-05'),
  },
  {
    id: 43,
    username: 'luke_alexander',
    firstName: 'Luke',
    lastName: 'Alexander',
    email: 'luke.alexander@example.com',
    birthDate: new Date('1986-04-10'),
    basicSalary: 70000,
    status: 'Active',
    group: 'Marketing',
    description: new Date('2022-09-10'),
  },
  {
    id: 44,
    username: 'sarah_hernandez',
    firstName: 'Sarah',
    lastName: 'Hernandez',
    email: 'sarah.hernandez@example.com',
    birthDate: new Date('1993-09-25'),
    basicSalary: 67000,
    status: 'Active',
    group: 'Engineering',
    description: new Date('2022-09-15'),
  },
  {
    id: 45,
    username: 'owen_miller',
    firstName: 'Owen',
    lastName: 'Miller',
    email: 'owen.miller@example.com',
    birthDate: new Date('1988-02-08'),
    basicSalary: 72000,
    status: 'Active',
    group: 'Sales',
    description: new Date('2022-09-20'),
  },
  {
    id: 46,
    username: 'hannah_bennett',
    firstName: 'Hannah',
    lastName: 'Bennett',
    email: 'hannah.bennett@example.com',
    birthDate: new Date('1995-07-22'),
    basicSalary: 69000,
    status: 'Active',
    group: 'Engineering',
    description: new Date('2022-09-25'),
  },
  {
    id: 47,
    username: 'carter_richardson',
    firstName: 'Carter',
    lastName: 'Richardson',
    email: 'carter.richardson@example.com',
    birthDate: new Date('1990-12-05'),
    basicSalary: 71000,
    status: 'Active',
    group: 'Marketing',
    description: new Date('2022-10-01'),
  },
  {
    id: 48,
    username: 'scarlett_ross',
    firstName: 'Scarlett',
    lastName: 'Ross',
    email: 'scarlett.ross@example.com',
    birthDate: new Date('1987-05-20'),
    basicSalary: 68000,
    status: 'Active',
    group: 'Engineering',
    description: new Date('2022-10-05'),
  },
  {
    id: 49,
    username: 'dylan_howard',
    firstName: 'Dylan',
    lastName: 'Howard',
    email: 'dylan.howard@example.com',
    birthDate: new Date('1994-10-15'),
    basicSalary: 70000,
    status: 'Active',
    group: 'Sales',
    description: new Date('2022-10-10'),
  },
  {
    id: 50,
    username: 'claire_morgan',
    firstName: 'Claire',
    lastName: 'Morgan',
    email: 'claire.morgan@example.com',
    birthDate: new Date('1991-03-30'),
    basicSalary: 67000,
    status: 'Active',
    group: 'Engineering',
    description: new Date('2022-10-15'),
  },
  {
    id: 51,
    username: 'lily_hall',
    firstName: 'Lily',
    lastName: 'Hall',
    email: 'lily.hall@example.com',
    birthDate: new Date('1995-08-12'),
    basicSalary: 69000,
    status: 'Active',
    group: 'Engineering',
    description: new Date('2022-10-20'),
  },
  {
    id: 52,
    username: 'gabriel_gomez',
    firstName: 'Gabriel',
    lastName: 'Gomez',
    email: 'gabriel.gomez@example.com',
    birthDate: new Date('1990-01-30'),
    basicSalary: 71000,
    status: 'Active',
    group: 'Sales',
    description: new Date('2022-10-25'),
  },
  {
    id: 53,
    username: 'scarlett_morris',
    firstName: 'Scarlett',
    lastName: 'Morris',
    email: 'scarlett.morris@example.com',
    birthDate: new Date('1993-06-10'),
    basicSalary: 68000,
    status: 'Active',
    group: 'Engineering',
    description: new Date('2022-11-01'),
  },
  {
    id: 54,
    username: 'ethan_bennett',
    firstName: 'Ethan',
    lastName: 'Bennett',
    email: 'ethan.bennett@example.com',
    birthDate: new Date('1988-11-25'),
    basicSalary: 70000,
    status: 'Active',
    group: 'Marketing',
    description: new Date('2022-11-05'),
  },
  {
    id: 55,
    username: 'aubrey_richardson',
    firstName: 'Aubrey',
    lastName: 'Richardson',
    email: 'aubrey.richardson@example.com',
    birthDate: new Date('1995-04-08'),
    basicSalary: 67000,
    status: 'Active',
    group: 'Engineering',
    description: new Date('2022-11-10'),
  },
  {
    id: 56,
    username: 'emma_watson',
    firstName: 'Emma',
    lastName: 'Watson',
    email: 'emma.watson@example.com',
    birthDate: new Date('1990-09-20'),
    basicSalary: 72000,
    status: 'Active',
    group: 'Sales',
    description: new Date('2022-11-15'),
  },
  {
    id: 57,
    username: 'jacob_jackson',
    firstName: 'Jacob',
    lastName: 'Jackson',
    email: 'jacob.jackson@example.com',
    birthDate: new Date('1987-02-15'),
    basicSalary: 69000,
    status: 'Active',
    group: 'Engineering',
    description: new Date('2022-11-20'),
  },
  {
    id: 58,
    username: 'mia_evans',
    firstName: 'Mia',
    lastName: 'Evans',
    email: 'mia.evans@example.com',
    birthDate: new Date('1994-07-30'),
    basicSalary: 71000,
    status: 'Active',
    group: 'Marketing',
    description: new Date('2022-11-25'),
  },
  {
    id: 59,
    username: 'william_thomas',
    firstName: 'William',
    lastName: 'Thomas',
    email: 'william.thomas@example.com',
    birthDate: new Date('1989-12-12'),
    basicSalary: 68000,
    status: 'Active',
    group: 'Engineering',
    description: new Date('2022-12-01'),
  },
  {
    id: 60,
    username: 'olivia_cook',
    firstName: 'Olivia',
    lastName: 'Cook',
    email: 'olivia.cook@example.com',
    birthDate: new Date('1992-05-25'),
    basicSalary: 70000,
    status: 'Active',
    group: 'Sales',
    description: new Date('2022-12-05'),
  },
  {
    id: 61,
    username: 'mason_scott',
    firstName: 'Mason',
    lastName: 'Scott',
    email: 'mason.scott@example.com',
    birthDate: new Date('1987-10-10'),
    basicSalary: 69000,
    status: 'Active',
    group: 'Engineering',
    description: new Date('2022-12-10'),
  },
  {
    id: 62,
    username: 'ava_adams',
    firstName: 'Ava',
    lastName: 'Adams',
    email: 'ava.adams@example.com',
    birthDate: new Date('1995-03-22'),
    basicSalary: 71000,
    status: 'Active',
    group: 'Marketing',
    description: new Date('2022-12-15'),
  },
  {
    id: 63,
    username: 'logan_nelson',
    firstName: 'Logan',
    lastName: 'Nelson',
    email: 'logan.nelson@example.com',
    birthDate: new Date('1990-08-05'),
    basicSalary: 68000,
    status: 'Active',
    group: 'Engineering',
    description: new Date('2022-12-20'),
  },
  {
    id: 64,
    username: 'sophia_carter',
    firstName: 'Sophia',
    lastName: 'Carter',
    email: 'sophia.carter@example.com',
    birthDate: new Date('1986-01-28'),
    basicSalary: 70000,
    status: 'Active',
    group: 'Sales',
    description: new Date('2022-12-25'),
  },
  {
    id: 65,
    username: 'aiden_gonzalez',
    firstName: 'Aiden',
    lastName: 'Gonzalez',
    email: 'aiden.gonzalez@example.com',
    birthDate: new Date('1993-06-12'),
    basicSalary: 69000,
    status: 'Active',
    group: 'Engineering',
    description: new Date('2023-01-01'),
  },
  {
    id: 66,
    username: 'grace_hall',
    firstName: 'Grace',
    lastName: 'Hall',
    email: 'grace.hall@example.com',
    birthDate: new Date('1988-11-25'),
    basicSalary: 71000,
    status: 'Active',
    group: 'Marketing',
    description: new Date('2023-01-05'),
  },
  {
    id: 67,
    username: 'noah_morales',
    firstName: 'Noah',
    lastName: 'Morales',
    email: 'noah.morales@example.com',
    birthDate: new Date('1995-04-08'),
    basicSalary: 68000,
    status: 'Active',
    group: 'Engineering',
    description: new Date('2023-01-10'),
  },
  {
    id: 68,
    username: 'hannah_brooks',
    firstName: 'Hannah',
    lastName: 'Brooks',
    email: 'hannah.brooks@example.com',
    birthDate: new Date('1990-09-20'),
    basicSalary: 70000,
    status: 'Active',
    group: 'Sales',
    description: new Date('2023-01-15'),
  },
  {
    id: 69,
    username: 'logan_rivera',
    firstName: 'Logan',
    lastName: 'Rivera',
    email: 'logan.rivera@example.com',
    birthDate: new Date('1987-02-15'),
    basicSalary: 69000,
    status: 'Active',
    group: 'Engineering',
    description: new Date('2023-01-20'),
  },
  {
    id: 70,
    username: 'sophia_kelly',
    firstName: 'Sophia',
    lastName: 'Kelly',
    email: 'sophia.kelly@example.com',
    birthDate: new Date('1992-07-30'),
    basicSalary: 71000,
    status: 'Active',
    group: 'Marketing',
    description: new Date('2023-01-25'),
  },
  {
    id: 71,
    username: 'ethan_cox',
    firstName: 'Ethan',
    lastName: 'Cox',
    email: 'ethan.cox@example.com',
    birthDate: new Date('1986-12-12'),
    basicSalary: 68000,
    status: 'Active',
    group: 'Engineering',
    description: new Date('2023-02-01'),
  },
  {
    id: 72,
    username: 'olivia_howard',
    firstName: 'Olivia',
    lastName: 'Howard',
    email: 'olivia.howard@example.com',
    birthDate: new Date('1994-05-25'),
    basicSalary: 70000,
    status: 'Active',
    group: 'Sales',
    description: new Date('2023-02-05'),
  },
  {
    id: 73,
    username: 'william_gomez',
    firstName: 'William',
    lastName: 'Gomez',
    email: 'william.gomez@example.com',
    birthDate: new Date('1991-10-10'),
    basicSalary: 69000,
    status: 'Active',
    group: 'Engineering',
    description: new Date('2023-02-10'),
  },
  {
    id: 74,
    username: 'olivia_russell',
    firstName: 'Olivia',
    lastName: 'Russell',
    email: 'olivia.russell@example.com',
    birthDate: new Date('1986-03-22'),
    basicSalary: 71000,
    status: 'Active',
    group: 'Marketing',
    description: new Date('2023-02-15'),
  },
  {
    id: 75,
    username: 'noah_bennett',
    firstName: 'Noah',
    lastName: 'Bennett',
    email: 'noah.bennett@example.com',
    birthDate: new Date('1993-08-05'),
    basicSalary: 68000,
    status: 'Active',
    group: 'Engineering',
    description: new Date('2023-02-20'),
  },
  {
    id: 76,
    username: 'amelia_adams',
    firstName: 'Amelia',
    lastName: 'Adams',
    email: 'amelia.adams@example.com',
    birthDate: new Date('1988-01-28'),
    basicSalary: 70000,
    status: 'Active',
    group: 'Sales',
    description: new Date('2023-02-25'),
  },
  {
    id: 77,
    username: 'aiden_jackson',
    firstName: 'Aiden',
    lastName: 'Jackson',
    email: 'aiden.jackson@example.com',
    birthDate: new Date('1995-06-10'),
    basicSalary: 69000,
    status: 'Active',
    group: 'Engineering',
    description: new Date('2023-03-01'),
  },
  {
    id: 78,
    username: 'emma_morris',
    firstName: 'Emma',
    lastName: 'Morris',
    email: 'emma.morris@example.com',
    birthDate: new Date('1990-11-25'),
    basicSalary: 71000,
    status: 'Active',
    group: 'Marketing',
    description: new Date('2023-03-05'),
  },
  {
    id: 79,
    username: 'logan_scott',
    firstName: 'Logan',
    lastName: 'Scott',
    email: 'logan.scott@example.com',
    birthDate: new Date('1987-04-08'),
    basicSalary: 68000,
    status: 'Active',
    group: 'Engineering',
    description: new Date('2023-03-10'),
  },
  {
    id: 80,
    username: 'sophia_cook',
    firstName: 'Sophia',
    lastName: 'Cook',
    email: 'sophia.cook@example.com',
    birthDate: new Date('1994-09-20'),
    basicSalary: 70000,
    status: 'Active',
    group: 'Sales',
    description: new Date('2023-03-15'),
  },
  {
    id: 81,
    username: 'jacob_evans',
    firstName: 'Jacob',
    lastName: 'Evans',
    email: 'jacob.evans@example.com',
    birthDate: new Date('1989-02-15'),
    basicSalary: 69000,
    status: 'Active',
    group: 'Engineering',
    description: new Date('2023-03-20'),
  },
  {
    id: 82,
    username: 'mia_adams',
    firstName: 'Mia',
    lastName: 'Adams',
    email: 'mia.adams@example.com',
    birthDate: new Date('1992-07-30'),
    basicSalary: 71000,
    status: 'Active',
    group: 'Marketing',
    description: new Date('2023-03-25'),
  },
  {
    id: 83,
    username: 'william_cox',
    firstName: 'William',
    lastName: 'Cox',
    email: 'william.cox@example.com',
    birthDate: new Date('1986-12-12'),
    basicSalary: 68000,
    status: 'Active',
    group: 'Engineering',
    description: new Date('2023-04-01'),
  },
  {
    id: 84,
    username: 'olivia_howard',
    firstName: 'Olivia',
    lastName: 'Howard',
    email: 'olivia.howard@example.com',
    birthDate: new Date('1994-05-25'),
    basicSalary: 70000,
    status: 'Active',
    group: 'Sales',
    description: new Date('2023-04-05'),
  },
  {
    id: 85,
    username: 'noah_gomez',
    firstName: 'Noah',
    lastName: 'Gomez',
    email: 'noah.gomez@example.com',
    birthDate: new Date('1991-10-10'),
    basicSalary: 69000,
    status: 'Active',
    group: 'Engineering',
    description: new Date('2023-04-10'),
  },
  {
    id: 86,
    username: 'amelia_russell',
    firstName: 'Amelia',
    lastName: 'Russell',
    email: 'amelia.russell@example.com',
    birthDate: new Date('1986-03-22'),
    basicSalary: 71000,
    status: 'Active',
    group: 'Marketing',
    description: new Date('2023-04-15'),
  },
  {
    id: 87,
    username: 'aiden_bennett',
    firstName: 'Aiden',
    lastName: 'Bennett',
    email: 'aiden.bennett@example.com',
    birthDate: new Date('1993-08-05'),
    basicSalary: 68000,
    status: 'Active',
    group: 'Engineering',
    description: new Date('2023-04-20'),
  },
  {
    id: 88,
    username: 'emma_adams',
    firstName: 'Emma',
    lastName: 'Adams',
    email: 'emma.adams@example.com',
    birthDate: new Date('1988-01-28'),
    basicSalary: 70000,
    status: 'Active',
    group: 'Sales',
    description: new Date('2023-04-25'),
  },
  {
    id: 89,
    username: 'jacob_jackson',
    firstName: 'Jacob',
    lastName: 'Jackson',
    email: 'jacob.jackson@example.com',
    birthDate: new Date('1995-06-10'),
    basicSalary: 69000,
    status: 'Active',
    group: 'Engineering',
    description: new Date('2023-05-01'),
  },
  {
    id: 90,
    username: 'mia_morris',
    firstName: 'Mia',
    lastName: 'Morris',
    email: 'mia.morris@example.com',
    birthDate: new Date('1990-11-25'),
    basicSalary: 71000,
    status: 'Active',
    group: 'Marketing',
    description: new Date('2023-05-05'),
  },
  {
    id: 91,
    username: 'william_scott',
    firstName: 'William',
    lastName: 'Scott',
    email: 'william.scott@example.com',
    birthDate: new Date('1987-04-08'),
    basicSalary: 68000,
    status: 'Active',
    group: 'Engineering',
    description: new Date('2023-05-10'),
  },
  {
    id: 92,
    username: 'olivia_cook',
    firstName: 'Olivia',
    lastName: 'Cook',
    email: 'olivia.cook@example.com',
    birthDate: new Date('1992-09-20'),
    basicSalary: 70000,
    status: 'Active',
    group: 'Sales',
    description: new Date('2023-05-15'),
  },
  {
    id: 93,
    username: 'noah_evans',
    firstName: 'Noah',
    lastName: 'Evans',
    email: 'noah.evans@example.com',
    birthDate: new Date('1989-02-15'),
    basicSalary: 69000,
    status: 'Active',
    group: 'Engineering',
    description: new Date('2023-05-20'),
  },
  {
    id: 94,
    username: 'mia_adams',
    firstName: 'Mia',
    lastName: 'Adams',
    email: 'mia.adams@example.com',
    birthDate: new Date('1992-07-30'),
    basicSalary: 71000,
    status: 'Active',
    group: 'Marketing',
    description: new Date('2023-05-25'),
  },
  {
    id: 95,
    username: 'william_cox',
    firstName: 'William',
    lastName: 'Cox',
    email: 'william.cox@example.com',
    birthDate: new Date('1986-12-12'),
    basicSalary: 68000,
    status: 'Active',
    group: 'Engineering',
    description: new Date('2023-06-01'),
  },
  {
    id: 96,
    username: 'olivia_howard',
    firstName: 'Olivia',
    lastName: 'Howard',
    email: 'olivia.howard@example.com',
    birthDate: new Date('1994-05-25'),
    basicSalary: 70000,
    status: 'Active',
    group: 'Sales',
    description: new Date('2023-06-05'),
  },
  {
    id: 97,
    username: 'noah_gomez',
    firstName: 'Noah',
    lastName: 'Gomez',
    email: 'noah.gomez@example.com',
    birthDate: new Date('1991-10-10'),
    basicSalary: 69000,
    status: 'Active',
    group: 'Engineering',
    description: new Date('2023-06-10'),
  },
  {
    id: 98,
    username: 'amelia_russell',
    firstName: 'Amelia',
    lastName: 'Russell',
    email: 'amelia.russell@example.com',
    birthDate: new Date('1986-03-22'),
    basicSalary: 71000,
    status: 'Active',
    group: 'Marketing',
    description: new Date('2023-06-15'),
  },
  {
    id: 99,
    username: 'aiden_bennett',
    firstName: 'Aiden',
    lastName: 'Bennett',
    email: 'aiden.bennett@example.com',
    birthDate: new Date('1993-08-05'),
    basicSalary: 68000,
    status: 'Active',
    group: 'Engineering',
    description: new Date('2023-06-20'),
  },
  {
    id: 100,
    username: 'emma_adams',
    firstName: 'Emma',
    lastName: 'Adams',
    email: 'emma.adams@example.com',
    birthDate: new Date('1988-01-28'),
    basicSalary: 70000,
    status: 'Active',
    group: 'Sales',
    description: new Date('2023-06-25'),
  },
];
